services:
  db:
    restart: always
    image: postgres:15
    container_name: wallet_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_HOST=${POSTGRES_HOST_DOCKER}
    ports:
      - "${EXTERNAL_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wallet_network

  web:
    build: .
    container_name: wallet_service
    command: ["/wait-for-it.sh", "db:5432", "--", "bash", "-c", "python manage.py liquibase_migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "${BACKEND_SERVER_PORT}:${BACKEND_SERVER_PORT}"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - wallet_network

networks:
  wallet_network:
    driver: bridge
